services:
  - type: web
    name: congress-tracker-live
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: CONGRESS_API_KEY
        sync: false
